import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import type { Locale } from './i18n/locales'
import { DEFAULT_LOCALE } from './i18n/locales'

const CONTENT_ROOT = path.join(process.cwd(), 'src', 'content')

export type DocFrontmatter = {
  title: string
  description?: string
  /** Explicit ordering within a directory listing; lower sorts first. Ties
   * fall back to alphabetical by slug, same as Docusaurus's autogenerated
   * sidebar. Optional — most pages don't need it. */
  order?: number
}

export type DocPage = {
  /** e.g. ["components", "atoms", "button"] */
  slug: string[]
  frontmatter: DocFrontmatter
  content: string
  /** true when this locale had no translated file and English was served
   * instead — same graceful-fallback behavior as the Docusaurus site had. */
  isFallback: boolean
  filePath: string
}

function docsDir(locale: Locale): string {
  return path.join(CONTENT_ROOT, locale, 'docs')
}

/** Every doc's slug-path, enumerated from the English tree — the default
 * locale defines which pages *exist*; a translation only overrides one
 * page's *content*, never adds/removes pages (same model the Docusaurus
 * site used). */
export function getAllDocSlugs(): string[][] {
  const root = docsDir(DEFAULT_LOCALE)
  const slugs: string[][] = []

  function walk(dir: string, prefix: string[]) {
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry)
      if (statSync(full).isDirectory()) {
        walk(full, [...prefix, entry])
      } else if (entry.endsWith('.mdx') || entry.endsWith('.md')) {
        const name = entry.replace(/\.mdx?$/, '')
        slugs.push(name === 'index' ? prefix : [...prefix, name])
      }
    }
  }

  walk(root, [])
  return slugs
}

function resolveFilePath(locale: Locale, slug: string[]): string | null {
  const base =
    slug.length === 0 ? path.join(docsDir(locale), 'index') : path.join(docsDir(locale), ...slug)
  for (const ext of ['.mdx', '.md']) {
    if (existsSync(base + ext)) return base + ext
  }
  // A directory whose own index page is the slug itself, e.g. slug=["components"]
  // resolving to docs/components/index.mdx.
  for (const ext of ['.mdx', '.md']) {
    const indexPath = path.join(docsDir(locale), ...slug, 'index' + ext)
    if (existsSync(indexPath)) return indexPath
  }
  return null
}

export function getDocPage(locale: Locale, slug: string[]): DocPage | null {
  let filePath = resolveFilePath(locale, slug)
  let isFallback = false

  if (!filePath && locale !== DEFAULT_LOCALE) {
    filePath = resolveFilePath(DEFAULT_LOCALE, slug)
    isFallback = filePath !== null
  }

  if (!filePath) return null

  // Every route is statically generated from `src/content` at build time.
  // Avoid making Turbopack trace the whole repository from this already
  // resolved dynamic path into the server output.
  const raw = readFileSync(/* turbopackIgnore: true */ filePath, 'utf-8')
  const { data, content } = matter(raw)

  return {
    slug,
    frontmatter: data as DocFrontmatter,
    content,
    isFallback,
    filePath
  }
}

/** Sorted directory listing (files+dirs) for autogenerated sidebar sections
 * (components/atoms, /molecules, /organisms) — always reads the English
 * tree, same reasoning as getAllDocSlugs. */
export function listDocsInDir(
  dirSlug: string[]
): { slug: string[]; frontmatter: DocFrontmatter }[] {
  const dir = path.join(docsDir(DEFAULT_LOCALE), ...dirSlug)
  if (!existsSync(dir)) return []

  const results: { slug: string[]; frontmatter: DocFrontmatter }[] = []
  for (const entry of readdirSync(dir)) {
    if (entry === 'index.mdx' || entry === 'index.md') continue
    const full = path.join(dir, entry)
    if (statSync(full).isFile() && (entry.endsWith('.mdx') || entry.endsWith('.md'))) {
      const name = entry.replace(/\.mdx?$/, '')
      const raw = readFileSync(full, 'utf-8')
      const { data } = matter(raw)
      results.push({ slug: [...dirSlug, name], frontmatter: data as DocFrontmatter })
    }
  }

  return results.sort((a, b) => {
    const orderDiff = (a.frontmatter.order ?? 0) - (b.frontmatter.order ?? 0)
    if (orderDiff !== 0) return orderDiff
    return a.frontmatter.title.localeCompare(b.frontmatter.title)
  })
}
